In [1]:
import pandas as pd
import json
import os
#!pip install pyyaml
import yaml
from collections import defaultdict

In [2]:
# clone repository from github at https://github.com/openstates/people.git
folder_path = "data/us/legislature"
files = [f for f in os.listdir(folder_path) if f.endswith(".yml")]
# print the files
print(files)

['Kweisi-Mfume-79575558-ef44-5bb5-9c64-3d3fe3fb4427.yml', 'Carlos-A-Gimenez-9db37a87-2ba9-56a0-9b42-89697222e044.yml', 'Christopher-H-Smith-84a22f15-cf83-5f0b-a048-a6fc50aa60fe.yml', 'Michael-R-Turner-bac6c65d-846b-5e60-9532-fa216c99ccf6.yml', 'Eric-Schmitt-999df51b-9318-55b9-b0f6-d738ffc1d62d.yml', 'John-McGuire-f41db99d-4852-4347-ae03-5be5d66f5fe4.yml', 'Hillary-J-Scholten-55404260-10e4-59e0-b228-2a01a21fb952.yml', 'Raphael-G-Warnock-37f5a4b9-98b2-5c3d-857b-6e02f5123345.yml', 'Rand-Paul-7a1c13f9-1aac-5461-aa2a-11642749828d.yml', 'Robert-J-Wittman-0adba0f5-0723-584b-8071-3e442a01f2d2.yml', 'Eugene-Vindman-4ec4f784-d347-43e9-a473-907abbd8a6c7.yml', 'Josh-Gottheimer-8ce4e2db-be5a-5493-a399-b2e6061301ba.yml', 'Mike-Crapo-9243a3a9-4e91-5fc8-9643-ae46455b688b.yml', 'Vince-Fong-2d6b7f7f-a241-5064-9812-9506beb2b76e.yml', 'Vern-Buchanan-1e646f7b-600b-503f-9524-3ae95d00cd2d.yml', 'Sydney-Kamlager-Dove-1608d897-8cf1-5902-9e45-fbd0bbd72cca.yml', 'Bill-Cassidy-851546e4-4af0-5505-8a1c-4f2a83813589.yml', 'Nancy-Mace-c50627f5-6447-55e3-9ca9-183daf188b58.yml', 'Patty-Murray-eb3ab543-13a1-53db-a8a1-459e8e91b701.yml', 'Donald-G-Davis-33867761-33c6-5036-b3da-43fb485b65c9.yml', 'Margaret-Wood-Hassan-c59c2d02-3a1e-55a7-b1eb-638a902899d5.yml', 'Brad-Sherman-4015098b-d823-5776-9b47-ceb09bf523a9.yml', 'Elijah-Crane-e59ccc1e-b5f0-5b86-9b5b-a8fbf6038665.yml', 'Ritchie-Torres-3a4aef6c-28c5-5cb7-a664-0e8c9d0c4fd2.yml', 'Jake-Auchincloss-a68063b7-2ce8-5638-a836-4fa7b22b3432.yml', 'Ralph-Norman-9b2b75b5-2641-51be-91c3-9d14d40e4d1a.yml', 'Lisa-Murkowski-cd76253c-a786-586d-aaac-bd14db985c3b.yml', 'Troy-Downing-e7af88ed-3845-48da-aac8-a146688f1101.yml', 'John-Hoeven-18c027d3-52ca-5a48-a4d2-73167e382096.yml', 'Adriano-Espaillat-0d73f18d-36c1-526d-9d5c-5a0a63ff60af.yml', 'Robert-C-Bobby-Scott-b20b2d62-fa4a-5014-baac-2f86e1c691eb.yml', 'Haley-M-Stevens-62d84fce-0ff4-53df-b7a8-4c02d1dc8654.yml', 'Jodey-C-Arrington-4938e6be-7c14-536d-a559-91c74fcc17db.yml', 'Chuck-Edwards-1b8394c7-93d4-5a22-91cf-264782834b9b.yml', 'Tom-Cotton-a0c9885f-b9f8-5045-9e74-044a886b9a6e.yml', 'Celeste-Maloy-d242dd37-9f71-5412-9328-798305153967.yml', 'James-Lankford-62a44404-9be2-5bbc-b672-0ed5f1aba53d.yml', 'Austin-Scott-20c33933-79f5-58d1-834c-60779932257e.yml', 'Mike-Flood-51e14e3d-a2c7-5d16-81d5-6608049b5d7e.yml', 'Josh-Hawley-0a7d370e-88bd-5b83-9b93-c8607c036d7a.yml', 'Jess-G-Chuy-Garca-f89c416f-c08d-5251-9a31-201a5265e283.yml', 'Sam-Liccardo-79313847-d0b7-40fb-b76b-199803baf1c9.yml', 'Chris-Van-Hollen-6b768c01-2e7d-5316-9ece-d5e215648f85.yml', 'Terri-A-Sewell-f747c3f1-7247-5c91-9870-901ec617e884.yml', 'Daniel-S-Goldman-4c77555b-f35d-53ca-8c7d-7950b90a1b60.yml', 'Diana-DeGette-241df76f-7089-5821-ab7f-bb54d92ee9d7.yml', 'Don-Bacon-d409840c-63c1-53e4-9ff6-e5677cef9fe6.yml', 'John-James-f32918a9-b738-5f20-8c3e-f95c7fda80cb.yml', 'Gwen-Moore-0223a517-1c97-5425-8bca-2120c45ce2e5.yml', 'Kevin-Kiley-4aee9639-900f-5593-aab0-b55bb3e8da51.yml', 'John-Thune-342214ae-2e66-50a4-9a10-acc467bd5d98.yml', 'Daniel-Webster-04db1dc5-1903-5913-a439-fed236ff85a3.yml', 'Bernie-Moreno-a9a4d048-36e2-4f72-a764-5c361593a0d3.yml', 'Brian-Jack-8822d9c4-0917-4e09-89ae-7770a1e33ae4.yml', 'Jack-Reed-e62576aa-1bf5-5664-ad0f-b1fdbcdead56.yml', 'Nicole-Malliotakis-d47735a4-c407-5389-bfd2-f638ffccdd06.yml', 'Jefferson-Shreve-ae48c8d2-6f51-4bae-b6d1-b41130d20995.yml', 'Richard-Blumenthal-62fd9e8b-80ea-5484-b1f1-3f3b4c350cc3.yml', 'Chuck-Grassley-259d896b-e9b5-5237-9243-f5597ae0db7c.yml', 'Dale-W-Strong-e54a4532-aa1e-5e2d-b630-4f35ef10a46f.yml', 'Brandon-Gill-04d57494-1c70-423b-b063-63a9cdd60e6e.yml', 'Daniel-Meuser-df0edff1-f76c-5916-b28e-f70338b23a7a.yml', 'Tim-Walberg-9e622be4-95d2-5bf7-a99f-543d45400e82.yml', 'Robert-Garcia-48a4fe68-6141-50ff-8d0b-0693119fd250.yml', 'Brad-Knott-c4c7954c-f559-4dc5-8660-36bb53499283.yml', 'Mike-Kennedy-57bc6239-5c03-4ec4-960b-5f8a6e79644a.yml', 'Marilyn-Strickland-f0914f67-02b0-5f3c-8f03-949f79c30f62.yml', 'Pete-Aguilar-705749f4-c12c-5090-88fa-012d36611500.yml', 'James-C-Moylan-4f6d6ecb-8f69-5f40-9965-ac5fab1e3dba.yml', 'Paul-Tonko-19360ce3-5ad4-5b67-b253-0239a5360fbb.yml', 'Cory-A-Booker-d0bb2662-40b6-52d2-94e6-2bf9d588c954.yml', 'Kim-King-Hinds-45c8e926-9f2e-47e4-a2ff-69d3e74f674b.yml', 'Zoe-Lofgren-80764021-2b87-5b48-8999-98943700dea8.yml', 'Jeff-Merkley-96291b83-ea59-594a-97cf-630189e0b8ed.yml', 'W-Gregory-Steube-5fdae4c2-ba21-56a4-ae8c-5e95a175a90a.yml', 'Lauren-Underwood-9415f4f1-c2b8-5543-b695-d8cace3373f2.yml', 'Jasmine-Crockett-fafd6715-85a1-509b-98d1-6df68904f028.yml', 'James-E-Clyburn-e24e02a4-f70c-5b9e-84e2-eda2d153f80f.yml', 'Maria-Elvira-Salazar-23524e03-1206-50cb-844d-ddea47f258da.yml', 'Andrew-Ogles-5916e23e-c486-5d60-88c8-56bb65c23763.yml', 'Brendan-F-Boyle-d1509871-89c0-5f39-bc3d-b55e444e3909.yml', 'Virginia-Foxx-b77761e4-93cb-5fbb-972e-5d591198df8f.yml', 'Steve-Womack-b3fc0e27-b0a3-5106-ae4f-65d6cc93c031.yml', 'Yvette-D-Clarke-969d3e67-5686-5b4c-a8fe-5ec702a7343d.yml', 'Morgan-McGarvey-d9c43ab0-97c8-565b-80cf-9da35c1ccbee.yml', 'Mark-Alford-baf62641-318a-58be-bb76-f7c6aeb97684.yml', 'Jimmy-Panetta-946e688a-6b60-567e-bea7-893eb4364acc.yml', 'Jeff-Hurd-8c492331-43dd-4525-8f31-9b50cdc86818.yml', 'Jeanne-Shaheen-6d497134-2c53-5987-add8-6fffeaa96cda.yml', 'Tom-McClintock-173a4f3f-e38f-569e-97b2-e0424195f16c.yml', 'Debbie-Wasserman-Schultz-7bacff4a-1d4a-5c4f-a59c-311206c181d2.yml', 'Lori-Trahan-f8d561c8-c0f2-5251-9d52-53289b82c7d9.yml', 'Marc-A-Veasey-fe3cbb3c-90cd-5661-8f02-2e7da15459b8.yml', 'James-P-McGovern-d44223bc-5f00-56aa-be61-28b5a3b4429d.yml', 'Sam-Graves-82ed7662-b9c2-53f7-bab6-c2d59732128b.yml', 'Kelly-Morrison-ca26355f-2c52-4696-a1e9-0df7d965cdaf.yml', 'Zachary-Nunn-144ba1b8-981f-58d8-b85d-c38fca7d524c.yml', 'James-E-Risch-e8bb2501-1603-543f-9667-9089f781aa97.yml', 'Earl-L-Buddy-Carter-85e43f57-4901-52fd-9fad-57373277f5e1.yml', 'David-P-Joyce-b7ff0450-1acd-5127-b3f5-7246374119a9.yml', 'Brian-Schatz-bd24fe60-5756-5d23-bcbf-4734f366c257.yml', 'Al-Green-2ad84a53-f957-5a9c-861b-413aac608201.yml', 'Nancy-Pelosi-8056c810-7170-5009-88c3-a670ab30164b.yml', 'Mike-Kelly-72511635-46e3-536d-8880-b32c7cf3e470.yml', 'Michael-T-McCaul-15d37180-ddd2-5bb6-8dd4-cdd2690eca86.yml', 'Cory-Mills-e9c6e580-58c8-5a0c-a18c-d11c073a9964.yml', 'Grace-Meng-ae123357-c70e-5d29-b16f-2d17775ab0f6.yml', 'Ryan-K-Zinke-23aee4a1-f0aa-5803-9678-aebad9194f19.yml', 'David-Schweikert-100d00e0-275c-5bd0-960e-c24c3b50a8e5.yml', 'Michael-Cloud-da5e831e-227c-58a1-bf1a-86782158fb57.yml', 'John-Kennedy-7a996578-ee76-59c8-856c-4f63861a62da.yml', 'Deb-Fischer-1e87267c-1e9f-5e46-a266-b1d557a8571b.yml', 'Derek-Schmidt-36a3cc6d-57a7-4312-a979-f6a17ae40c93.yml', 'Greg-Stanton-3300ee9c-6602-5be9-9bb5-2fb7f65a8d5c.yml', 'Donald-S-Beyer-Jr-63d110f3-ccdb-5783-9d6a-4a7103f30c01.yml', 'Neal-P-Dunn-cebc95c4-7c20-58c5-829c-c3391f0761fa.yml', 'Josh-Riley-64be0348-ad79-4c2f-b548-babc5c27203c.yml', 'Tina-Smith-f82067c3-a257-54ae-b6bd-ebe5178372e7.yml', 'Betty-McCollum-61c4224a-c1d6-5739-bca6-0db7e58d84bd.yml', 'Scott-Perry-2ac15c4d-4052-5a49-9b5c-70b93a4e325e.yml', 'Mike-Haridopolos-14507f9f-01e6-449a-ba78-41ce2c8e20fd.yml', 'Monica-De-La-Cruz-c03dd126-0872-5937-9967-68aedb1ab964.yml', 'Lloyd-Smucker-0f2326f2-b5dc-5428-bcaa-9a1078d0750c.yml', 'Ron-Johnson-67d8f8b5-1fad-5132-9da8-3210783163a8.yml', 'Angela-Alsobrooks-93f7b243-f3e6-4fec-b65a-42f7a19939e3.yml', 'Kevin-Cramer-b18c868c-a789-5a02-8070-c0c473d55304.yml', 'Suhas-Subramanyam-3c344094-40c3-4550-be0c-a1e28191218c.yml', 'Jahana-Hayes-1d87ca8c-1a95-531f-bbdd-34e1679d45d2.yml', 'James-Comer-57b0c699-cef2-5740-bd15-4ad2562f8975.yml', 'Linda-T-Snchez-b01048a9-27a5-5fed-b5ef-7bf3b3be6d04.yml', 'Lisa-C-McClain-f8a1c19c-3aa4-5c20-a8a4-211a40b2c540.yml', 'Robert-E-Latta-2158a719-5cfa-5c41-92f7-4f0853782d2b.yml', 'Rudy-Yakym-III-bf37099b-56fe-54fe-acc1-a6d79a0107d1.yml', 'Harold-Rogers-8b8caa4b-52c1-54aa-bb51-bd0bccdc69b9.yml', 'Derrick-Van-Orden-b96b406a-d60a-57fe-96d1-c1dd5b189ab1.yml', 'Frank-J-Mrvan-c6c1c65f-7735-5ebb-951c-56d6cacc8ebb.yml', 'Sylvia-R-Garcia-168e0e9e-0d4c-57d2-99a6-8fc99be594be.yml', 'Janice-D-Schakowsky-c5e8693c-dca3-5ff7-b456-e71d944e4fb0.yml', 'Emanuel-Cleaver-8ea538b9-6af5-5683-8b4b-9061f89691c1.yml', 'Bradley-Scott-Schneider-a3c68bbd-f241-52c8-a7e9-7f340f316b7a.yml', 'Ken-Calvert-3ca12a7a-5192-58bf-ba92-c219af17d74c.yml', 'Trent-Kelly-c495bde9-29b3-5e71-ab0e-dedff0de9a84.yml', 'Tim-Burchett-06b83e26-fe35-526d-86fb-7a6d80b20d1a.yml', 'Jim-Costa-8d953afe-9b42-5c80-9f43-4ccf8af79513.yml', 'Ami-Bera-79c4f42e-4775-5ed0-a7e1-d0c942ce6c34.yml', 'Susie-Lee-4333db3d-a55e-5d8e-b2ec-1041414ba2e6.yml', 'Nanette-Diaz-Barragn-5ec7a759-2c3a-5270-8328-13c7ac611580.yml', 'Laura-Gillen-e7d0d7bb-61cf-4c53-87be-4a5025756498.yml', 'Thomas-Massie-7d1234be-d22a-5374-8022-59a795f0f3f4.yml', 'Chellie-Pingree-78a440e5-f314-5f5b-930b-48ab822bb39a.yml', 'Michael-F-Bennet-16a0a125-6ebe-58b3-810f-df10c0e7df1f.yml', 'Ted-Lieu-b472f29c-b960-5cea-b5fb-0e9d4d6d10a4.yml', 'Doris-O-Matsui-5262c34c-a015-5290-9ca4-3b6ec86f4b1d.yml', 'Thomas-H-Kean-Jr-1cbf8801-61cd-5f46-93c1-0d02f110035a.yml', 'Steven-Horsford-980a78cc-847f-50be-8967-6c8895ad337e.yml', 'Suzan-K-DelBene-799d9723-1f90-5558-b8c6-6f293c7eaddd.yml', 'Roger-Williams-e77e9595-b0fb-5923-a051-9f3221d8d6a9.yml', 'Mariannette-Miller-Meeks-fc8623ea-be1e-518f-aa76-3598910fa676.yml', 'Tommy-Tuberville-0ee1b661-2035-5dc1-ab1c-b87d25682775.yml', 'Joyce-Beatty-47fb8c8b-1c71-5c66-9781-94be94803332.yml', 'Josh-Brecheen-68651247-63fc-5dad-8071-4efef949f7fd.yml', 'Nellie-Pou-8bbf0452-cf85-4f36-9cf6-20f232746407.yml', 'John-Garamendi-d4381c32-b267-5e35-b118-c0da3a0a80a1.yml', 'Andy-Kim-62227c11-1ad4-5395-b233-f1f526efc5b4.yml', 'Tom-Emmer-08e42c4f-2c5e-5fe0-87cf-0e8de2bdb52d.yml', 'J-French-Hill-73ff0305-598d-5558-9b5e-6834be8a503a.yml', 'Jon-Ossoff-4e48da38-17ab-5580-bced-2ea00b9b2843.yml', 'Madeleine-Dean-1daf07ea-2575-511e-a5a8-47f0662cf209.yml', 'Kim-Schrier-eb152f16-def8-5b51-9379-e7e463628ad6.yml', 'Deborah-K-Ross-ea21df34-9ef4-5746-b83a-700bdc2d1918.yml', 'Thomas-P-Tiffany-5048bd11-acf0-5775-a75f-5f085fc8bc11.yml', 'Pat-Harrigan-5f9a4c31-5f85-4197-8137-e16a15e63d2e.yml', 'Jason-Crow-fb2f7d0c-f39b-50a6-8bdc-8bdc181683bc.yml', 'Kevin-Hern-139e15e1-4a50-5126-ad7a-b462c44f00e0.yml', 'Pat-Fallon-425d847d-6fbf-55a7-a117-76bca5e3f299.yml', 'Beth-Van-Duyne-861bd195-d8aa-5e72-9699-4f5ad3d5e499.yml', 'Pablo-Jos-Hernndez-1d2ca024-3e33-4da9-b759-0d4bfdec43e9.yml', 'Mike-Collins-0f7a88d1-4e4c-565a-b905-706181d7b561.yml', 'Yassamin-Ansari-0e94bb34-dc2e-47d2-8953-ed3bfe2d21f2.yml', 'Val-T-Hoyle-8d143b3d-646a-5199-95f5-497e17f386dd.yml', 'Tracey-Mann-675e8a3b-ea68-55f8-aeb8-be287fe621bd.yml', 'Julia-Letlow-2a914bb0-5ddc-52d0-abb0-f0cd7830fc5f.yml', 'Mark-DeSaulnier-a1d66d4f-5f94-5605-9e25-96c8f5b4e2df.yml', 'Darren-Soto-ef44884b-f8bf-542b-b1ae-f36c7cf8e962.yml', 'Michael-Baumgartner-fee60ecb-32b2-404d-854d-c180d3d2138f.yml', 'Sheri-Biggs-295e47f2-b86f-4b98-a111-7f05b57427c6.yml', 'James-A-Himes-e1a8d4da-7cbd-571e-817d-774ff06bb342.yml', 'David-Rouzer-5e9726e3-2aae-5708-9227-0e95ac43c203.yml', 'Bob-Onder-9a7bd8c6-7ddc-4cc0-9764-f210aef357bf.yml', 'Dan-Sullivan-a6b5e853-563f-5b87-a14a-a1427f56b262.yml', 'Sheldon-Whitehouse-fd0623ac-bbc8-5c5e-839f-37148d89c36e.yml', 'Darin-LaHood-a7bc3999-648e-58ed-b606-f387e825427c.yml', 'Mark-E-Amodei-e58ac762-d546-52f3-8efd-8a2c8f12f731.yml', 'Wesley-Bell-0555dc1b-b9eb-4d13-99aa-25b1c4349f83.yml', 'Tim-Kaine-4d537f5f-04fd-578a-a8d2-61dd4972e758.yml', 'Richard-J-Durbin-7d0c4665-2bcf-5e53-b450-25461cd13d85.yml', 'Ashley-Moody-cb582ab6-6a5a-4578-9e44-620c9a6a1f4c.yml', 'Michael-Guest-6b015607-c3dd-5867-a1bb-733bf84fe091.yml', 'Mike-Quigley-b8578429-a84d-5542-a903-02feaee3a7d4.yml', 'Paul-A-Gosar-5eae38e3-8420-5c09-831a-db73d9cba978.yml', 'John-B-Larson-4d2b82fc-189e-5007-980f-64a85612afdb.yml', 'Luz-Rivas-4b3b1061-3118-449e-9088-cd50f2556b69.yml', 'Richard-Hudson-18943ddd-9052-5b22-905b-65ff2ac3abf7.yml', 'Alexandria-Ocasio-Cortez-d2a8d710-a781-5a40-b6f2-e46bffcf40d2.yml', 'William-R-Keating-ec0f62a4-5b85-5df2-888a-200166766b17.yml', 'George-Whitesides-b7094a5e-a819-465f-a716-54ad6cad5207.yml', 'Jennifer-L-McClellan-6d89e5cc-c605-55ff-ba4d-b3d58d6ac1af.yml', 'Alma-S-Adams-76bfaf2b-8259-5f56-bce9-d1c8cd6c780d.yml', 'Lateefah-Simon-aa578bb8-0e69-45d5-ba94-d52d6043caf1.yml', 'Nicholas-A-Langworthy-a4321566-0258-5d46-bc51-c1f77ba95ba0.yml', 'Ed-Case-20f1a4db-1281-5e3f-9d6d-657a3f178b3f.yml', 'Michael-A-Rulli-91ba3b6a-a4c8-54ab-8964-8498641a6d8f.yml', 'Michelle-Fischbach-66724fb4-e553-59cb-b8ba-314e3bf9f1ea.yml', 'John-R-Curtis-7cc5139d-8e53-560c-9828-926395e1552d.yml', 'Tom-Barrett-4651a84b-e450-46d2-abd0-3778a7c9912a.yml', 'Stephen-F-Lynch-cc7120d8-f57d-5841-9526-3429e9f0f2c2.yml', 'Harriet-M-Hageman-17005404-0e78-5bcc-8a71-d67af0e033fd.yml', 'Mark-Takano-d01bffb6-a515-5ca5-8203-3a9b8d5da15e.yml', 'Derek-Tran-f1c19dd9-8fe6-43ce-bdd6-97a4932b1694.yml', 'Emily-Randall-df6e4f59-2370-45bc-9370-cd0db74dc661.yml', 'Ted-Cruz-c4d35f64-f25b-5888-9fcb-f3cb97df500e.yml', 'Nydia-M-Velzquez-bc18d350-32b2-5e37-8b43-6f85ae9b5b09.yml', 'Laurel-M-Lee-96350e36-02c1-512a-8b83-fdd0dd93be88.yml', 'Summer-L-Lee-e2bd9b69-7425-5f80-b432-41b690306379.yml', 'Robert-Menendez-a516a327-22fc-57af-931b-f28926b44b85.yml', 'Dave-Taylor-68bb620b-21e6-42a5-8575-6be621f1d8d1.yml', 'Mike-Ezell-fef4e629-aa7e-5bc5-9128-abfce1af96d5.yml', 'Bill-Huizenga-ce06af2e-4591-560d-8f14-8f1817c9ad1f.yml', 'Bernard-Sanders-a1ec37b6-9f54-529a-8165-ff96e9d8d93e.yml', 'Keith-Self-404f8ca3-d216-5c95-b5aa-17176b25aa16.yml', 'Chris-Pappas-22a8725b-acc8-530a-9a57-6b0a7f750fca.yml', 'Brian-J-Mast-e7b50abf-92e8-56f1-a5f7-7db9a63fb43f.yml', 'Eric-Swalwell-032302ae-d513-5e31-bafc-8bc3cbb18d7c.yml', 'Salud-O-Carbajal-a106e70c-7857-5d7c-8252-5f4768818ef2.yml', 'Maxine-Dexter-21c437a3-faa2-486e-a6e6-b2fb9ce68da2.yml', 'Troy-A-Carter-5e3dc0b5-2afe-5b83-ab42-9352225b2235.yml', 'Nick-Begich-b0cf2626-c728-4970-bf18-bb30ea91c229.yml', 'Ronny-Jackson-417128fd-ee37-5676-988d-263b908aa027.yml', 'John-W-Rose-a30feb1f-c9fe-5612-808e-8fe5a55b76dc.yml', 'Marcy-Kaptur-b6f3dafd-0c6e-5694-ac20-59a88e891f62.yml', 'Shelley-Moore-Capito-793e5b46-2682-51ff-bfca-adf217ca9a65.yml', 'Richard-E-Neal-882d0f96-61bb-57b0-9683-c72425d337e9.yml', 'Greg-Casar-3b0de391-3f75-564b-9b1c-c793300ff1a9.yml', 'Jacky-Rosen-2f7f8ec5-f652-5c47-8dcb-06d7bc54557c.yml', 'Jared-Huffman-c2b08e7d-2372-5af6-b333-7ea2787cb3ca.yml', 'John-Joyce-50b75c29-4e98-5622-b60f-59485dcc1141.yml', 'Juan-Vargas-904bef1f-7ef4-51af-aeef-b0ac8e1fbe06.yml', 'Mario-Diaz-Balart-7e5729d1-198d-5389-be51-d1e05969729c.yml', 'Lizzie-Fletcher-b2b37c5e-17c0-5833-b5e0-fe4f93834761.yml', 'Eric-Sorensen-42d739b0-f570-5d50-b549-eeaa2c7507ee.yml', 'Jerrold-Nadler-d6cd4f62-7c5f-5595-ac5e-4e40741e5f3b.yml', 'Danny-K-Davis-a494987e-6674-5df8-a8b2-de4b5a99de86.yml', 'Charles-J-Chuck-Fleischmann-640abb7e-8890-59bc-b5cb-b21c88288657.yml', 'Johnny-Olszewski-9069b9f9-6884-4f31-80ff-0b53c697ce3b.yml', 'Andr-Carson-ef4b4ed3-1808-548d-8625-2cea913c2e4a.yml', 'Gary-C-Peters-edbfabfd-d26b-5d22-9a5d-f079181608f8.yml', 'Dan-Crenshaw-6e2bcde3-a1f5-5296-9f9f-88c71885f3db.yml', 'Jared-Moskowitz-356c2159-c402-51d8-b4eb-697aaff46dc2.yml', 'Mark-E-Green-92fdf72b-20aa-5d08-83b8-833c4714b0ac.yml', 'Aumua-Amata-Coleman-Radewagen-eb3fa86b-690c-5cc0-8f5e-54af60f28a06.yml', 'Troy-Balderson-7ba189b5-1c2a-5acd-8118-446326a8e02b.yml', 'John-Boozman-b352dd8b-dd06-57b0-833a-2b0b3bd33ad6.yml', 'Maria-Cantwell-46c3b77a-7d00-5ecc-83d0-04c8fa05bf04.yml', 'Greg-Landsman-63dfcb23-8196-5bd6-a5cc-b6592d99150e.yml', 'Josh-Harder-3ed77541-5a79-56b1-94d9-79baa74e938b.yml', 'Mazie-K-Hirono-ee89a520-227a-575d-8379-5d36b6e6b2a2.yml', 'Brad-Finstad-bc26b71a-566f-57fd-9d5b-23bc27e4c4a4.yml', 'Rick-W-Allen-4cdf55a7-a62e-5b3d-a07f-305f4e9dc5c1.yml', 'Sean-Casten-89f8b007-1bf3-589a-bffe-92acf526f448.yml', 'David-G-Valadao-cf552a34-e9e1-5de9-9270-b5b441dd89fe.yml', 'Shontel-M-Brown-f2916088-1774-50ba-8023-34f7fe686e49.yml', 'Peter-Welch-8addb5a8-a569-54b2-811b-b5d091350411.yml', 'Tammy-Baldwin-d7c97bc3-b7cb-585b-b9e3-def97fcb9db6.yml', 'Steve-Cohen-e56dabed-c7b4-51c2-a29b-c9850bc9feff.yml', 'Ruben-Gallego-256da84c-1b8a-5d48-99ba-9c9f7dd2d310.yml', 'Brian-K-Fitzpatrick-a6a4c673-58ba-587b-b36b-7a559c379f23.yml', 'Max-L-Miller-a26ef77d-1f50-5c77-918d-83f917ac83fb.yml', 'Tim-Scott-3bb4a99e-9448-5b35-86cd-114bd035535e.yml', 'Charles-E-Schumer-ced62f94-88a6-5a4b-b470-89cf1ee4bdac.yml', 'Eric-Burlison-6a54b336-ad96-5ceb-a963-50fe0f56c288.yml', 'Abe-Hamadeh-87b6bc67-1685-4f6e-bf7f-ada3083ec638.yml', 'Chip-Roy-2398f81d-6371-544d-a7ff-24cf993a716b.yml', 'Rob-Bresnahan-669b83bc-8b17-4b14-b45f-b760cf704126.yml', 'David-Kustoff-5beaa710-fc70-563c-9842-f885e13d9aea.yml', 'Stephanie-I-Bice-2add0122-3206-5502-985b-18808db8f685.yml', 'Gregory-F-Murphy-b66a5d85-c9cd-5689-a482-d175230ab86d.yml', 'Mike-Levin-ac0c3c4b-14c8-5bc1-bb8b-001af291ee3d.yml', 'Joni-Ernst-86133add-b3ff-52c2-a71e-442b9afeff6b.yml', 'Lance-Gooden-8d52be7e-dba0-5b01-bb9a-c0cfb72fa609.yml', 'Seth-Moulton-7cdb552c-a069-5bae-8c32-c42a2f6c04f6.yml', 'Jim-Banks-befb976c-1369-5d86-a53f-4aeebdf486cc.yml', 'Jefferson-Van-Drew-a7706596-7110-5866-935b-b44668b92af1.yml', 'John-R-Moolenaar-cb38b814-2794-505a-9232-f1bd56ca3ca0.yml', 'Elise-M-Stefanik-febd3b9d-501f-5191-aaff-87666a5af603.yml', 'H-Morgan-Griffith-562f0794-c1fb-50ee-b69c-3a01b25cfc3a.yml', 'Nikema-Williams-132a1bba-204a-5d4f-a406-40b4342bad1b.yml', 'Frank-D-Lucas-90a2bdbf-1b51-5e72-aef9-5a98c305f31d.yml', 'Amy-Klobuchar-2722e0b1-650d-5f77-a348-f7f0d66aa3e2.yml', 'Claudia-Tenney-21f20fe0-1075-512d-99a6-cafcebf57d20.yml', 'Russ-Fulcher-59f2dee7-1c9f-588e-a8ca-158e054f7fca.yml', 'Christopher-A-Coons-792faee4-b972-54ed-b42d-47b41a22ccb3.yml', 'Mark-Messmer-da7c34ba-9642-49fe-bde9-b274101ef680.yml', 'Brittany-Pettersen-4f00239f-feef-59fa-87de-5a62e277bb5f.yml', 'Jon-Husted-caec878c-2749-45e6-99a3-9bf077bf07e7.yml', 'Pete-Stauber-54c25fbc-b91d-5d2b-8403-9b8fb1fb6792.yml', 'John-Mannion-cbf45e94-7411-4e5a-a6af-eaaad3a3fd68.yml', 'John-R-Carter-7b014168-dc13-5568-96df-8c7cbb335268.yml', 'Andrew-R-Garbarino-4ec1dbc4-ea21-5f61-92b1-fa55b47a4c61.yml', 'Cindy-Hyde-Smith-3827ab20-4901-56bc-a6ea-e7c275da9eb9.yml', 'William-R-Timmons-IV-678a7e1c-3834-5536-937f-fdb30edca68e.yml', 'Bill-Hagerty-fb408324-49e1-56ad-8425-65c2a1e88103.yml', 'Sharice-Davids-70056f40-1938-557d-be5d-ddb841c9f19a.yml', 'Adam-Gray-f45073ab-65cc-4117-a7d3-e89584ff430e.yml', 'Julie-Fedorchak-f90457e1-c4f0-4805-8411-6fa218ec0d82.yml', 'Delia-C-Ramirez-34d76857-187b-5f62-a2d1-ddfcd13494cf.yml', 'Steny-H-Hoyer-5554fdf4-9035-5d23-aeb0-fee7d786fa81.yml', 'Alex-Padilla-fadd82ac-5031-5efd-ae39-1afc3f3cd6fb.yml', 'Mark-Kelly-30665d55-5695-5ede-930d-c92e63e4ee65.yml', 'Jared-F-Golden-3c47a44a-29b8-5aa1-b61a-9e49ea0caf99.yml', 'Pete-Ricketts-e1b9405a-e695-5bc5-b3b0-6cdc1415f53c.yml', 'Marie-Gluesenkamp-Perez-3d465b8f-2f67-5283-8cab-da3990ec8c49.yml', 'Scott-H-Peters-379b2f6a-82e3-572b-a471-75020486662e.yml', 'Andy-Biggs-86b4b077-b73b-579b-bb73-bc5a4a73719a.yml', 'Adam-B-Schiff-c5a3238c-f36a-5b17-af62-ca6dcce0b91d.yml', 'Shomari-Figures-df368e3b-72b7-4608-a291-9eb0c0b78eec.yml', 'Dave-Min-a1120307-ef30-48b0-8d6a-74df54cb7739.yml', 'August-Pfluger-2519c079-f97e-532b-b53e-167398fd7398.yml', 'Andrea-Salinas-54f931b7-9a94-5c93-8585-0967370ffb86.yml', 'Maxine-Waters-fc7a4a9e-9274-546f-ae5c-bcf46f3fe0f2.yml', 'James-R-Baird-749232ec-b66c-5bd7-b828-10a466b95f0a.yml', 'Andrew-S-Clyde-0dbe5471-29ea-5c84-8270-f55fee08d118.yml', 'Glenn-Ivey-3e53830a-108c-5864-92f1-9f9c8f7b1d0f.yml', 'Hakeem-S-Jeffries-f06d8480-e875-5184-8316-4140a912a03d.yml', 'April-McClain-Delaney-da3caabf-f9ad-4138-9b19-6a90076a870f.yml', 'Richard-McCormick-3056cc98-9ca1-5293-8064-fc12fd9c689f.yml', 'Julie-Johnson-ea06a401-ba19-4028-8986-38e950a657b6.yml', 'Adam-Smith-55a28978-7661-5a33-a2be-a505a07e2a8e.yml', 'Mike-Carey-e2402add-94f2-53fa-9f40-69ba590c744f.yml', 'Mike-Johnson-ef2a1e73-edb7-5f53-9f61-da2020fc417d.yml', 'David-Scott-e6650822-1063-5485-b062-d169ea173ec2.yml', 'Thom-Tillis-3ad2df38-e817-50b9-924d-9dbd4bba94a8.yml', 'Elizabeth-Warren-3de20aaf-f982-5aa3-8280-c5154be829aa.yml', 'Laura-F

In [3]:
# Convert all the yaml files to a dataframe
rows = []

# First pass: gather all possible identifier schemes
all_schemes = set()

for file in files:
    with open(os.path.join(folder_path, file), 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)
        for id_obj in data.get("other_identifiers", []):
            all_schemes.add(id_obj.get("scheme"))

# Now process each file with all identifier columns
for file in files:
    with open(os.path.join(folder_path, file), 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)

        # Prepare default row
        row = defaultdict(lambda: None)

        # Basic fields
        row["id"] = data.get("id")
        row["name"] = data.get("name")
        row["given_name"] = data.get("given_name")
        row["family_name"] = data.get("family_name")
        row["birth_date"] = data.get("birth_date")
        row["gender"] = data.get("gender")
        row["email"] = data.get("email")
        row["image"] = data.get("image")
        row["party"] = data.get("party", [{}])[0].get("name")

        # Roles
        role = data.get("roles", [{}])[-1]
        row["role_type"] = role.get("type")
        row["district"] = role.get("district")
        row["role_start_date"] = role.get("start_date")
        row["role_end_date"] = role.get("end_date")

        # Social media (if available)
        for k, v in data.get("ids", {}).items():
            row[f"social_{k}"] = v

        # Other identifiers
        for id_obj in data.get("other_identifiers", []):
            scheme = id_obj.get("scheme")
            identifier = id_obj.get("identifier")
            row[f"{scheme}_id"] = identifier

        rows.append(row)

# Create DataFrame
df = pd.DataFrame(rows)

# Fill in missing columns for any scheme not found in every legislator
for scheme in all_schemes:
    col_name = f"{scheme}_id"
    if col_name not in df.columns:
        df[col_name] = None

In [4]:
df.columns

Index(['id', 'name', 'given_name', 'family_name', 'birth_date', 'gender',
       'email', 'image', 'party', 'role_type', 'district', 'role_start_date',
       'role_end_date', 'social_twitter', 'social_facebook', 'ballotpedia_id',
       'bioguide_id', 'fec_id', 'google_entity_id_id', 'govtrack_id',
       'house_history_id', 'icpsr_id', 'opensecrets_id', 'pictorial_id',
       'thomas_id', 'votesmart_id', 'wikidata_id', 'wikipedia_id',
       'social_youtube', 'cspan_id', 'maplight_id', 'lis_id'],
      dtype='object')

In [5]:
df.head()

,id,name,given_name,family_name,birth_date,gender,email,image,party,role_type,...,opensecrets_id,pictorial_id,thomas_id,votesmart_id,wikidata_id,wikipedia_id,social_youtube,cspan_id,maplight_id,lis_id
0,ocd-person/79575558-ef44-5bb5-9c64-3d3fe3fb4427,Kweisi Mfume,Kweisi,Mfume,1948-10-24,Male,https://mfume.house.gov/address_authentication...,https://unitedstates.github.io/images/congress...,Democratic,lower,...,N00001799,13090,00798,26892,Q519504,NaN,NaN,NaN,NaN,NaN
1,ocd-person/9db37a87-2ba9-56a0-9b42-89697222e044,Carlos Giménez,Carlos,Giménez,1954-01-17,Male,https://gimenez.house.gov/contact,https://unitedstates.github.io/images/congress...,Republican,lower,...,N00046394,13009,NaN,81366,Q5041653,Carlos A. Giménez,NaN,NaN,NaN,NaN
2,ocd-person/84a22f15-cf83-5f0b-a048-a6fc50aa60fe,Chris Smith,Chris,Smith,1953-03-04,Male,https://chrissmith.house.gov/contact/zipauth.htm,https://unitedstates.github.io/images/congress...,Republican,lower,...,N00009816,13153,01071,26952,Q981167,Chris Smith (New Jersey politician),UCtCNUDo3-I1gsd_03ppDfZg,6411,469,NaN
3,ocd-person/bac6c65d-846b-5e60-9532-fa216c99ccf6,Mike Turner,Mike,Turner,1960-01-11,Male,https://turner.house.gov/email-me,https://unitedstates.github.io/images/congress...,Republican,lower,...,N00025175,13204,01741,45519,Q505722,Mike Turner,UC-6Ss-aZ3OPisf9GdVGtN8g,1003607,496,NaN
4,ocd-person/999df51b-9318-55b9-b0f6-d738ffc1d62d,Eric Schmitt,Eric,Schmitt,1975-06-20,Male,https://www.schmitt.senate.gov/contact/,https://unitedstates.github.io/images/congress...,Republican,upper,...,N00048414,13416,NaN,104474,Q5387455,NaN,NaN,NaN,NaN,S420

In [6]:
df[["id", "name", "bioguide_id"]]

,id,name,bioguide_id
0,ocd-person/79575558-ef44-5bb5-9c64-3d3fe3fb4427,Kweisi Mfume,M000687
1,ocd-person/9db37a87-2ba9-56a0-9b42-89697222e044,Carlos Giménez,G000593
2,ocd-person/84a22f15-cf83-5f0b-a048-a6fc50aa60fe,Chris Smith,S000522
3,ocd-person/bac6c65d-846b-5e60-9532-fa216c99ccf6,Mike Turner,T000463
4,ocd-person/999df51b-9318-55b9-b0f6-d738ffc1d62d,Eric Schmitt,S001227
...,...,...,...
533,ocd-person/86b65fd7-4549-51fa-80e8-eaf3daf3e60e,Lou Correa,C001110
534,ocd-person/10de7024-4b40-57b0-ae78-101372fd4a02,Pat Ryan,R000579
535,ocd-person/39f36070-b860-5345-a3cc-ea7fdbf7dfb3,Adrian Smith,S001172
536,ocd-person/74d8d6c8-c349-4fe7-ae18-62c69c4f8d4b,Craig Goldman,G000601
537,ocd-person/bb0d60f6-19a4-5229-a67d-a1d428e7c0b2,Ben Cline,C001118

In [10]:
# are there any missing bioguide ids?
df[df['bioguide_id'].isna()].head()

Empty DataFrame
Columns: [id, name, given_name, family_name, birth_date, gender, email, image, party, role_type, district, role_start_date, role_end_date, social_twitter, social_facebook, ballotpedia_id, bioguide_id, fec_id, google_entity_id_id, govtrack_id, house_history_id, icpsr_id, opensecrets_id, pictorial_id, thomas_id, votesmart_id, wikidata_id, wikipedia_id, social_youtube, cspan_id, maplight_id, lis_id]
Index: []

[0 rows x 32 columns]

In [11]:
# Save file to csv
df.to_csv("plural_legislators_with_bioguide.csv", index=False)